name: Build
on: [push, pull_request]
env:
  SSH_KEY: ${{ secrets.SSH_KEY }}
  DOWNLOAD_SERVER: ${{ secrets.DOWNLOAD_SERVER }}
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-15, macos-15-arm, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'ffc071e0c08432c60c9b64f00334c0227667931b'

      - name: Build project
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ runner.os }}
          buildPreset: 'default'
